name: Build CSharp Windows App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore BidirectionalViewer.sln

      - name: Build Application
        run: msbuild BidirectionalViewer.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReceiverApp-Release
          path: '**/bin/Release/**'
          if-no-files-found: error
